services:

  backend:
    image: ghcr.io/mutimtemki/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    image: ghcr.io/mutimtemki/frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

  telegram-bot:
    image: ghcr.io/mutimtemki/telegram-bot:latest
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
